spring.application.name=jobportal
spring.security.user.name=user
spring.security.user.password=user

spring.datasource.url=jdbc:postgresql://localhost:5433/jobportal
spring.datasource.username=postgres
spring.datasource.password=Abhishek@911
spring.jpa.hibernate.ddl-auto=update